### PR TITLE
DPC-4433: Tag and deploy static site

### PR DESCRIPTION
**Pull request by jdettmannnava**
## 🎫 Ticket

https://jira.cms.gov/browse/DPC-4433

## 🛠 Changes

- Deploy Workflow added
- Release Workflow added

## ℹ️ Context

We are moving from Jenkins to Github actions for our deployments. These workflows duplicate:
- [Jenkinsfile.deploy_static_site](https://github.com/CMSgov/dpc-ops/blob/main/jenkins_files/Jenkinsfile.deploy_static_site)
- [Jenkinsfile.release_static_site](https://github.com/CMSgov/dpc-ops/blob/main/jenkins_files/Jenkinsfile.release_static_site)

## 🧪 Validation

Release (which includes deploy) ran successfully: https://github.com/CMSgov/dpc-static-site/actions/runs/12377126243/job/34545914298
Note: The run pointed to a branch of dpc-app and was run on push (which has since been removed). Will test inputs when available.

### CODE REVIEW

**Comment by lukey-luke** [comment]
I double checked and it looks like the appropriate bucket is selected for the action for prod vs non-prod. We might want to merge https://github.com/CMSgov/dpc-app/pull/2358 first, which is a dependency for release.yml (e.g. see failed job [here](https://github.com/CMSgov/dpc-static-site/actions/runs/12377662558)).

Is there any way to run these? Based on the `workflow_dispatch` documentation [HERE](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_dispatch), it looks like it needs to be part of `main`. So unless I'm missing something, we should probably merge this in and then verify output via "Run workflow"

**Comment by jdettmannnava** [comment]
> I double checked and it looks like the appropriate bucket is selected for the action for prod vs non-prod. We might want to merge [CMSgov/dpc-app#2358](https://github.com/CMSgov/dpc-app/pull/2358) first, which is a dependency for release.yml (e.g. see failed job [here](https://github.com/CMSgov/dpc-static-site/actions/runs/12377662558)).
> 
> Is there any way to run these? Based on the `workflow_dispatch` documentation [HERE](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_dispatch), it looks like it needs to be part of `main`. So unless I'm missing something, we should probably merge this in and then verify output via "Run workflow"

I did link a successful run in the description. The way I was running it was adding an 'on push' dispatcher, which was still there and I just removed.
Since it is new and does not run automatically, I think it would be fine to approve this pull request (and the one in dpc-app) but not consider the ticket closed until both workflows successfully ran from main.

**Comment by chris-ronning-ny** [comment]
The way @jdettmannnava described that is how I did it for https://github.com/CMSgov/dpc-app/pull/2356. I think that's more than sufficient.

**Review by chris-ronning-ny — APPROVED** [review]

**Comment by jdettmannnava** [comment]
Successful deploy: https://github.com/CMSgov/dpc-static-site/actions/runs/12561744090
Successful tag and deploy: https://github.com/CMSgov/dpc-static-site/actions/runs/12561890963/job/35021532565

**Pull request merged**
